export default ([
  {
    code: 'de',
    status: 'beta',
    name: 'Deutsch',
    eng_name: 'Deutsch',
    img: () => import('@/assets/images/lang/de.svg'),
},
  {
    code: 'en',
    status: 'stable',
    name: 'English',
    eng_name: 'English',
    img: () => import('@/assets/images/lang/en.svg'),
  },
  {
    code: 'es',
    status: 'beta',
    name: 'Español',
    eng_name: 'Spanish',
    img: () => import('@/assets/images/lang/es.svg'),
  },
  {
    code: 'fr',
    status: 'beta',
    name: 'Français',
    eng_name: 'French',
    img: () => import('@/assets/images/lang/fr.svg'),

  },
  {
    code: 'ru',
    status: 'stable',
    name: 'Русский',
    eng_name: 'Russian',
    img: () => import('@/assets/images/lang/ru.svg'),
  },
  {
    code: 'zh',
    status: 'beta',
    name: '汉语',
    eng_name: 'Chinese',
    img: () => import('@/assets/images/lang/zh.svg'),
  },
  {
    code: 'uk',
    status: 'beta',
    name: 'Українська',
    eng_name: 'Ukrainian',
    img: () => import('@/assets/images/lang/uk.svg'),
  },
  {
    code: 'by',
    status: 'beta',
    name: 'Беларуская',
    eng_name: 'Belarusian',
    img: () => import('@/assets/images/lang/by.svg'),
  },
  {
    code: 'ja',
    status: 'beta',
    name: '日本語',
    eng_name: 'Japanese',
    img: () => import('@/assets/images/lang/ja.svg'),
  },
]);